"""
AI Experts — Business Command Center
Central hub with SSO to Revenue Dashboard, Invoice Creator, Content Center, File Anonymizer.
"""
import os
import hmac
import hashlib
import time
import json
import threading
import uuid
import zipfile
import io
import tempfile
from pathlib import Path
from functools import wraps
from datetime import datetime

from flask import (Flask, render_template, request, redirect, url_for,
                   session, jsonify, send_file, Blueprint, flash)
from dotenv import load_dotenv

# ─── Load env ─────────────────────────────────────────────────────────────────
load_dotenv(dotenv_path=Path(__file__).parent / '.env')

BASE_DIR = Path(__file__).parent

# ─── App setup ────────────────────────────────────────────────────────────────
app = Flask(__name__)
app.secret_key = os.environ.get('CC_SECRET_KEY', 'cc-secret-please-change')
app.config['MAX_CONTENT_LENGTH'] = 200 * 1024 * 1024

CC_PASSWORD    = os.environ.get('CC_PASSWORD', 'changeme123')
CC_SSO_SECRET  = os.environ.get('CC_SSO_SECRET', 'cc-sso-shared-secret-change-me')
INVOICE_URL    = os.environ.get('INVOICE_URL', 'https://invoice.YOUR_DOMAIN')
DASHBOARD_URL  = os.environ.get('DASHBOARD_URL', 'https://dashboard.YOUR_DOMAIN')

# Media / content paths
MEDIA_DIR     = BASE_DIR / 'media'

# ─── SSO token helpers ────────────────────────────────────────────────────────

def _generate_sso_token() -> str:
    """Create a signed time-limited token for invoice app SSO."""
    ts  = str(int(time.time()))
    sig = hmac.new(CC_SSO_SECRET.encode(), ts.encode(), hashlib.sha256).hexdigest()
    return f"{ts}.{sig}"


def verify_sso_token(token: str, max_age: int = 90) -> bool:
    """Verify a token generated by _generate_sso_token."""
    try:
        ts, sig = token.split('.', 1)
        expected = hmac.new(CC_SSO_SECRET.encode(), ts.encode(), hashlib.sha256).hexdigest()
        if not hmac.compare_digest(sig, expected):
            return False
        return (int(time.time()) - int(ts)) <= max_age
    except Exception:
        return False


# ─── Auth decorator ───────────────────────────────────────────────────────────

def login_required(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        if not session.get('cc_logged_in'):
            return redirect(url_for('login', next=request.path))
        return f(*args, **kwargs)
    return decorated


# ─── Core routes ──────────────────────────────────────────────────────────────

@app.route('/login', methods=['GET', 'POST'])
def login():
    if session.get('cc_logged_in'):
        return redirect(url_for('dashboard'))
    error = None
    if request.method == 'POST':
        if request.form.get('password', '') == CC_PASSWORD:
            session['cc_logged_in']  = True
            session.permanent        = True
            nxt = request.form.get('next') or url_for('dashboard')
            return redirect(nxt)
        error = 'Incorrect password. Please try again.'
    return render_template('login.html', error=error,
                           next=request.args.get('next', ''))


@app.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('login'))


@app.route('/')
@login_required
def dashboard():
    return render_template('dashboard.html')


# ─── SSO launch routes ────────────────────────────────────────────────────────

@app.route('/launch/revenue')
@login_required
def launch_revenue():
    token = _generate_sso_token()
    return redirect(f"{DASHBOARD_URL}/cc-auth?token={token}&next=/")


@app.route('/launch/invoice')
@login_required
def launch_invoice():
    token = _generate_sso_token()
    return redirect(f"{INVOICE_URL}/cc-auth?token={token}&next=/")


# ─── Content Center ───────────────────────────────────────────────────────────

@app.route('/content')
@login_required
def content():
    return render_template('content.html')


@app.route('/api/content')
@login_required
def api_content():
    """Return media content JSON for the content center."""
    result = {
        'linkedin_posts': [],
        'videos':         [],
        'latest_blog':    None,
    }

    # LinkedIn posts
    posts_file = MEDIA_DIR / 'posts.json'
    if posts_file.exists():
        try:
            data = json.loads(posts_file.read_text())
            result['linkedin_posts'] = data.get('posts', [])
        except Exception:
            pass

    # YouTube videos
    videos_file = MEDIA_DIR / 'videos.json'
    if videos_file.exists():
        try:
            data = json.loads(videos_file.read_text())
            result['videos'] = data.get('videos', [])
        except Exception:
            pass

    # Latest blog post — read from media/blog_posts.json if present
    blog_file = MEDIA_DIR / 'blog_posts.json'
    if blog_file.exists():
        try:
            data = json.loads(blog_file.read_text())
            posts = data.get('posts', [])
            if posts:
                result['latest_blog'] = posts[-1]
        except Exception:
            pass

    return jsonify(result)


# ─── PII Cleaner Blueprint ────────────────────────────────────────────────────
# Imported lazily to avoid heavy imports slowing startup if Azure libs missing.

try:
    from pii_blueprint import pii_bp
    app.register_blueprint(pii_bp, url_prefix='/pii')
except ImportError as e:
    print(f"[warn] PII blueprint not loaded: {e}")


# ─── Entry point ──────────────────────────────────────────────────────────────

if __name__ == '__main__':
    app.run(debug=False, host='0.0.0.0', port=5003)
